[DRAFT] Nodes reload secure settings
elastic/elastic-client-generator pull request #108
Opened 2021-02-04 16:10 UTC by philkra

as titled.

Need to complete the response.

2021-02-05 15:15 UTC, delvedor requested changes

2021-02-05 15:15 UTC, delvedor commented on specification/specs/cluster/reload_secure_settings/ReloadSecureSettingsRequest.ts
> +    secure_settings_password: string
This should be optional :)
```suggestion
    secure_settings_password?: string
```

2021-02-19 07:22 UTC, delvedor reviewed
@philkra everything looks good here, can you regenerate the output?

2021-02-22 10:58 UTC, philkra commented
@delvedor : https://github.com/elastic/elastic-client-generator/pull/108#pullrequestreview-593918504 --> done

2021-03-01 14:17 UTC, delvedor approved these changes
LGTM

2021-03-01 14:17 UTC, merged