Validated Snapshot.* endpoints
elastic/elastic-client-generator pull request #209
Opened 2021-03-15 20:14 UTC by philkra

* `snapshot.create_repository` request
* `snapshot.get_repository` response
* `snapshot.create` response

2021-03-15 20:32 UTC, Mpdreamz submitted a review, later dismissed
LGTM

2021-03-16 07:03 UTC, delvedor requested changes
LGTM

Can you re-run `make contrib`?

2021-03-16 08:43 UTC, philkra commented
@delvedor reran `make contrib`

2021-03-16 08:44 UTC, delvedor approved these changes

2021-03-16 08:44 UTC, merged