Fix ml.update_job Request
elastic/elastic-client-generator pull request #310
Opened 2021-04-03 14:03 UTC by philkra

as titled.

2021-04-06 11:33 UTC, delvedor requested changes
LGTM, can you fix the conflicts and regenerate the output?

2021-04-12 13:13 UTC, philkra commented
@delvedor conflicts resolved

2021-04-19 13:24 UTC, delvedor commented on specification/__common/ml/ModelPlotConfigEnabled.ts
> +   * stability: experimental
Should we add a `stability` tag for properties as well?

2021-04-19 13:24 UTC, delvedor approved these changes
LGTM

2021-04-19 13:24 UTC, merged