Validate rank_eval API
elastic/elastic-client-generator pull request #334
Opened 2021-04-12 18:08 UTC by philkra

as titled.

2021-04-16 17:43 UTC, philkra commented
all conflicts resolved and ready for new schema.

2021-04-19 12:23 UTC, delvedor requested changes
The changes look ok, but you should add `export ` to all class definitions.

2021-04-19 12:30 UTC, philkra commented
added exports.

2021-04-19 13:16 UTC, delvedor approved these changes
LGTM

2021-04-19 13:16 UTC, merged