Cat Aliases
elastic/elastic-client-generator pull request #73
Opened 2021-01-20 15:52 UTC by philkra

Added request & response without the CSV validation.

2021-01-20 16:51 UTC, Mpdreamz requested changes

2021-01-20 16:51 UTC, Mpdreamz commented on specification/specs/cat/cat_aliases/CatAliasesRequest.ts
> +    expand_wildcards?: ExpandWildcards | Array<ExpandWildcards>;
I think the better fix would be:

```
export enum ExpandWildcardsOptions {
..
}

export type ExpandWildcards = ExpandWildcardsOptions | Array<ExpandWildcardsOptions> 
```

This should fix all usages of `ExpandWildcards`

2021-01-21 08:05 UTC, Mpdreamz submitted a review, later dismissed

2021-01-21 08:47 UTC, philkra commented
added suggested improvements

2021-01-21 08:48 UTC, delvedor approved these changes
LGTM

2021-01-21 08:48 UTC, merged